ALTER TABLE "LudoGame" ADD COLUMN "playerOneRoomPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LudoGame" ADD COLUMN "playerTwoRoomPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LudoGame" ADD COLUMN "rewardGranted" BOOLEAN NOT NULL DEFAULT false;

